### ISSUE TITLE
[SN1998bp] <Descriptive issue title>

### ISSUE THREAD

**Issue by MikeFoly** [astrocatalogs/supernovae#103]
Duplicate data with/without errors again.  It appears that various CfA light curves are taken from both the CfA archive (with errors) and Sternberg (without errors).  This appears to be both for Riess et al. and Jha et al. datasets.

**Comment by guillochon** [comment]
The data with error bars appears to originate from bibcodes `2006AJ....131..527J` (Jha et al.) and `1999AJ....117..707R` (Riess et al.), I've blacklisted these two bibcodes [here](https://github.com/astrocatalogs/supernovae/commit/cee771f0c42a432374bd2e065ba13781d657fcb6) from ITEP so that will hopefully solve this issue and leave only the data with error bars. Again 24 hours before changes live.

**Comment by MikeFoly** [comment]
Great, thanks a lot James!

**Comment by guillochon** [comment]
This appears to be fixed now on the live page, closing.
