### ISSUE TITLE
[SN1572A] Incorrect/additional photometry reference?

### ISSUE THREAD

**Issue by astrofoley** [astrocatalogs/supernovae#128]
The photometry is referenced to Guillochon et al. (2017), but the photometry doesn't seem to be in that paper.  It looks similar to the Ruiz–Lapuente compilation but with some differences.  Regardless, the original sources (presumably Brahe, Munoz, Praetorius, etc) should be referenced in addition to any paper that quantifies or "adjusts" the photometry.

**Comment by guillochon** [comment]
Looks like this might be a subtle bug relating to the way aliases are defined (using the deprecated `aliases` key) given that the original sources are properly attributed in the input file. This event should be fixed by https://github.com/astrocatalogs/sne-internal/commit/04fb0418dfb98813523accfc7bcb0c2b740baa64, but the aliases bug persists for now, I'll leave this issue open until it's fixed.

**Comment by guillochon** [comment]
Yep replacing that deprecated key fixed this. I'll try and track down the underlying bug, likely anything with an `aliases` key in the `sne-internal` repo is affected by a similar misattribution if those files present any photometry.
