### ISSUE TITLE
[PS1-11bdn] <Redshift wrong>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#131]
Should be 0.738 - Lunnan et al. (2017) [2017arXiv170801619L]

Looks like currently listed redshift (0.522) is simply a transcription error - this is the redshift of a neighbouring object in the PS1 SLSN table

**Comment by guillochon** [comment]
Fixed in https://github.com/astrocatalogs/sne-internal/commit/d5bea5c21f1de35a55cb5d6331105ecbf5222014.

Can you check a few other entries from that paper to make sure the redshifts are correct?

PS1-10ahf
PS1-10awh
PS1-10bzj
PS1-10ky
PS1-10pm
PS1-11afv
PS1-11aib
PS1-11ap
PS1-11bam
PS1-11bdn
PS1-11tt
PS1-12bmy
PS1-12bqf
PS1-12cil
PS1-13gt
PS1-13or
PS1-14bj

**Comment by mnicholl** [comment]
All the others are correct

**Comment by guillochon** [comment]
Great, closing.
