### ISSUE TITLE
[SN2012dn] SN possibly scrubbed from database?

### ISSUE THREAD

**Issue by rrgupta** [astrocatalogs/supernovae#138]
Hi,
The following API query worked a couple days ago, but now returns "No objects found within specified search region.":
https://api.astrocats.space/catalog/alias+ra+dec+claimedtype+redshift?ra=305.9010&dec=-28.2787&radius=60
I still have the .json I saved from this query, but now this SN (a.k.a PSN J20233626-2816434) seems to have been scrubbed from the database recently for some reason. I wanted to look up the SN on the web https://sne.space/sne/SN2012dn but this page now redirects to SN2002dn. Any idea what happened?

Thanks,
Ravi

**Comment by guillochon** [comment]
Good question, it does appear to have been scrubbed. I'll investigate.

**Comment by guillochon** [comment]
So the HTML page failed to render last night for this object (due to a bug), which automatically excludes it from the catalog listing. I am re-rendering all the HTML pages now, which should fix this and https://github.com/astrocatalogs/supernovae/issues/137. Will update this issue once that is done.

**Comment by guillochon** [comment]
All pages have been regenerated and this object has re-appeared. Thanks very much for pointing out this issue!

**Comment by rrgupta** [comment]
Thanks for fixing it so quickly! 
BTW all my API queries are now giving "502 Bad Gateway" errors. Is some maintenance still being done?
