### ISSUE TITLE
Import shortcomings since conversion to OO

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/supernovae#14]
Currently the import script has a few bugs that need to be worked out before the new import script is used on the web:

- [x] `KM/s` instead of `km/s` for velocity units.
- [x] `u_time` missing from most (all?) photometry.
- [x] Some sources end up without a `name` field; all sources should have a name.
- [x] Entries being dumped into wrong year, being moved into previous year range (e.g. supernovae from 2000-2004 are found in 1990-1999).
- [x] Derived attribute missing from derived parameters.
- [x] Host galaxy scrubbing not working (e.g. Anon. in SN1999L).
- [x] Maximum time missing from some supernovae (e.g. SN1999L).
- [x] Most photometry from ITEP not being added.
- [x] Aliases not been scrubbed before being added (e.g. SN2002cx has "SN 2002cx" and "2002cx" as aliases; both should have been converted to "SN2002cs" by `clean_name` before they were added.

**Comment by jparrent** [comment]
@guillochon Most everything looks great! I've looked through about 30 household SNe thus far and have come up with the following:

- [ ] all of SN1987A is missing
- [ ] SN2012dn is missing spectra from WISeREP
- [ ] SN2009dn is missing spectra from WISeREP
- [ ] SN1992A missing a lot of spectra
- [ ] SN1991bg. This issue is the same for old and new versions, but the spectra in the viewer are not top-to-bottom by epoch. See below and find the bright neon green ones near the top. One of them needs to be removed, I'll get after that one.

![screen shot 2016-07-18 at 8 10 29 pm](https://cloud.githubusercontent.com/assets/7276612/16934576/86203628-4d25-11e6-96b9-44c8bd2f1d4a.png)

**Comment by guillochon** [comment]
@jparrent I had thought the event rebuild had completed, but it hadn't quite yet when I sent the e-mail; 1987A is there now (and so should everything else).

As for the other spectra-related points, the current version isn't using the "spider" input just yet. Are the spectra consistent with what was available in the old WISeREP collection, before the spider?

**Comment by raffaellamargutti** [comment]
It seems that for NGC6946SNR J203451500+60090910, z, v, dl did not make it to the new version.

**Comment by jparrent** [comment]
@guillochon Ah right, I suspected this might be the case for 87A and new spectra from WISeREP but wanted to mention anyway. Thank you!

**Comment by guillochon** [comment]
@jparrent I have now put the "spider" into the live webpage. Could you check your SNe on your checklist to see if they have the expected spectra?

**Comment by jparrent** [comment]
@guillochon Success! This is now working for the spectra from WISeREP. 

As for 1992A, it appears the spectra are not being pulled from sne-external-spectra/Superfit.

**Comment by guillochon** [comment]
It looks like all of these issues have been addressed, so I'll close this for now, and will open individual issues if anything else new crops up.
