### ISSUE TITLE
Use all bands in maximum determination, add new visual maximum

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#41]
m_max and date of maximum seem to be reported for the brightest r-band point, which is nowhere near light curve maximum

**Comment by guillochon** [comment]
@mnicholl So I don't think this is a "bug" per se, rather a case of missing data. If the maximum isn't noted anywhere, the OSC uses the maximum brightness available (and it's date) as the maximum.

Happen to know where a full dataset for this one is? Or at least, its true time of max?

**Comment by mnicholl** [comment]
Right but what I mean is that there are clearly brighter data points on the plot that it’s not using!

**Comment by guillochon** [comment]
Ah, so the reason for this is the derived maximum have preferred bands that are used first, here's the current order:

```Python
['B', 'b', 'g'],  # B-like bands first
['V', 'G'],       # if not, V-like bands
['R', 'r']        # if not, R-like bands
```

The reason this is done is because maximum dates in the literature seem to prefer using B band when no bolometric LC is available. I'm not sure of an easy fix here without constructing pseudo-bolometric LCs. Any suggestions on a best practice?

**Comment by guillochon** [comment]
So this is being addressed by adding a new "visual maximum" set of keys to the `SUPERNOVA` class that will using the original logic mentioned above, whereas the originate "maximum" keys will now using the brightest magnitude measurement, in any band. The table on the OSC will use the new "maximum" as the default. I'll probably add the apparent visual maximum/date to the table as well as a new column (hidden by default), just so that people who are interested in that can still see it. I'll close once the catalog successfully updates.

**Comment by guillochon** [comment]
This change is now live, closing.
