### ISSUE TITLE
[SN2016aps] <mag value rather than band name in legend>

### ISSUE THREAD

**Issue by mnicholl** [astrocatalogs/supernovae#44]
The y band limits are labelled "18.3" in the legend

**Comment by guillochon** [comment]
Yeah this was a weird bug where Bokeh will interpret the legend labels as variables, if a legend label matches one of the axis names (in this case y), it uses the y-value rather than the band name.

For this event in particular it will be fixed with a full web rebuild later today. I'll close when I verify it's fixed.

**Comment by guillochon** [comment]
OK fixed this one here: https://github.com/astrocatalogs/astrocats/commit/9eb7ab65ce85abf5d07d052a688d13cb463eec1f, had just neglected to fix the labels for the upper limit points, they were already fixed for the detections. Closing.
