### ISSUE TITLE
[SN2008Q] Wrong redshift.

### ISSUE THREAD

**Issue by pbrown801** [astrocatalogs/supernovae#71]
The redshift for SN2008Q's host appears wrong.  NED reports NGC 524 has a redshift of 0.008016 while OSA lists 	0.000908064, 0.000916468

**Comment by guillochon** [comment]
Thanks @pbrown801! Definitely something funny going on here, I'll look into it.

**Comment by guillochon** [comment]
So @pbrown801 this appears to be an error in NED-D, the comoving distance reported for SN2008Q specifically is way off from all the other reported distances of NGC 504 (4 Mpc instead of 28 Mpc). Here's the snippet from the NED-D file (bad values in bold):

<pre>
"","16369","3839","NGC 0524","31.51","0.12","20.0","GCLF","2001AJ....121.2974L","","","","","21","blue GCs, TOM(V) = -7.17 mag"
"","16370","3839","NGC 0524","32.14","0.09","26.8","GCLF","2001AJ....121.2974L","","","","","21","all GCs, TOM(V) = -7.63 mag"
"","16371","3839","NGC 0524","32.23","0.14","27.9","GCLF","2001AJ....121.2974L","","","","","21","red GCs, TOM(V) = -7.55 mag"
"","16372","3839","NGC 0524","31.60","","20.9","PNLF","2007ApJ...657...76F","","","","","27",""
"R","16373","3839","NGC 0524","31.80","","22.9","PNLF","2004AAS...205.6906J","","","","","24",""
"R","16374","3839","NGC 0524","28.02","0.10",<b>"4.02"</b>,"SNIa","2015Sci...347.1459K","SN 2008Q","","","","35","MLCS2k2, R(V) = 1.8"
"R","16375","3839","NGC 0524","28.04","0.08",<b>"4.06"</b>,"SNIa","2015Sci...347.1459K","SN 2008Q","","","","35","MLCS2k2, R(V) = 3.1"
"","16376","3839","NGC 0524","32.37","0.19","29.6","SNIa","2006ApJ...645..488W","SN 2000cx","0.00793","72","","26",""
"","16377","3839","NGC 0524","32.40","0.12","30.2","SNIa","2008MNRAS.389.1577T","SN 2000cx","","70.8","","28",""
"","16378","3839","NGC 0524","32.51","","31.8","SNIa","2003PASP..115..277C","SN 2000cx","","","","23","H"
"","16379","3839","NGC 0524","32.53","0.05","32.1","SNIa","2001PASP..113.1178L","SN 2000cx","","","","21","MLCS"
"","16380","3839","NGC 0524","31.74","0.20","22.3","SBF","2003ApJ...583..712J","","","","","23","I"
"","16381","3839","NGC 0524","31.90","0.14","24.0","SBF","2013AJ....146...86T","","","74.4","","33",""
"","16382","3839","NGC 0524","31.90","0.20","24.0","SBF","2001ApJ...546..681T","","","","","21","I"
"","16383","3839","NGC 0524","31.90","0.20","24.0","SBF","2001ApJ...559..584A","","","","","21","I"
"","16384","3839","NGC 0524","31.74","0.37","22.3","Faber-Jackson","1984ApJS...56...91D","","","95","","4","Weighted Mean"
"","16385","3839","NGC 0524","31.80","0.46","22.9","Faber-Jackson","1984ApJS...56...91D","","","95","","4","Michard 1979a"
"R","16386","3839","NGC 0524","31.86","","23.6","Faber-Jackson","2006sf2a.conf..365V","","","","","26","LEDA [April 2006]"
"","16387","3839","NGC 0524","31.97","0.69","24.8","Faber-Jackson","1984ApJS...56...91D","","","95","","4","de Vaucouleurs"
"","16388","3839","NGC 0524","32.14","0.63","26.8","Faber-Jackson","1984ApJS...56...91D","","","95","","4","Michard 1979b, c"
"","16389","3839","NGC 0524","31.83","0.25","23.2","Tertiary","1984ApJS...56...91D","","","95","","4",""
"","16390","3839","NGC 0524","32.53","0.80","32.1","Tully est","1988NBGC.C....0000T","","","75","","8","B"
"","16391","3839","NGC 0524","32.32","0.45","29.1","Tully-Fisher","2007A&A...465...71T","","","","","27","K"
"","16392","3839","NGC 0524","32.65","0.40","33.8","Tully-Fisher","2007A&A...465...71T","","","","","27","mean"
</pre>

I have e-mailed the NED maintainers to inform them. In the meantime I am marking the comoving distance from NED for SN2008Q as being erroneous: https://github.com/astrocatalogs/sne-internal/commit/749a3eddf277ccb21fc5b5d101c9934c58090886.

**Comment by guillochon** [comment]
I received a response from the NED folks:

> We think this is a typo too. In our defense, the typo is in the original article by Kelly et al. [2015Sci...347.1459K] and so NED is providing a faithful reproduction of the data published.

> Nevertheless, I am surprised we did not notice this ourselves, as the distance estimate for SN 2008Q published by Kelly et al. is highly discrepant compared to other estimates available. We are glad you caught this.

> Since the data appears to be in error, we will contact Patrick Kelly and politely inquire further. We will let you know what he says, as well as the best way to proceed with the discrepant data, once we know. Good eye, and thank you for contacting us.

**Comment by pbrown801** [comment]
So the distance from Kelly is wrong, but should the redshift be derived from the distance at all?  For nearby galaxies/supernovae not in the hubble flow, these aren't well correlated.

**Comment by guillochon** [comment]
The conversions are only done if the redshift is not available directly, which for 2008Q it doesn't seem to be. There is a minor bug here where the redshift is technically derived but is not marked as being such on the OSC, I will fix that.

In this case this is supposed to be the comoving distance to the supernova, so the converted value would be close if the distance weren't in error.

**Comment by guillochon** [comment]
Redshifts/distances for the hosts are used, if they are available, unless the redshift/distance is quoted for the supernova itself. It's not entirely clear what the best practice here is, at high redshift the supernovae should be in the Hubble flow and thus the high-precision host redshifts are probably the most accurate measures of distance, but at low redshift the host might have significant deviation from the Hubble flow, so it's not clear that the redshift can be directly related to distance (using the comoving from NED would be best, if it's available).

In this case I'm going to adjust the error specification to mark the Kelly paper, rather than NED, as being erroneous, then the OSC will use the median comoving distance to the galaxy from NED to estimate the distance.
